export const READ_PROPERTI = "properti/read_properti"
export const CREATE_PROPERTI = "properti/create_properti"
export const UPDATE_PROPERTI = "properti/update_properti"
export const REMOVE_PROPERTI = "properti/remove_properti"
export const READ_DETAIL_PROPERTI = "properti/read_detail_properti"

export const READ_USER = "user/read_user"
export const CREATE_USER = "user/create_user"
export const UPDATE_USER = "user/update_user"
export const REMOVE_USER = "user/remove_user"
export const READ_DETAIL_USER = "user/read_detail_user"
