export const READ_PROPERTI = "properti/read_properti"
export const CREATE_PROPERTI = "properti/create_properti"
export const UPDATE_PROPERTI = "properti/update_properti"
export const REMOVE_PROPERTI = "properti/remove_properti"
export const READ_DETAIL_PROPERTI = "properti/read_detail_properti"
